# Generated by Django 2.2 on 2019-04-12 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='telefone',
            field=models.CharField(max_length=16),
        ),
    ]
