# Generated by Django 2.2 on 2019-04-12 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0002_auto_20190412_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medico',
            name='cpf',
            field=models.CharField(max_length=14, unique=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='cpf',
            field=models.CharField(max_length=14, unique=True),
        ),
    ]
