# Generated by Django 2.2 on 2019-04-15 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0003_auto_20190412_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='hora',
            field=models.TimeField(default='00:00', unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='consulta',
            name='data',
            field=models.DateField(unique=True),
        ),
    ]
